[package]
name = "jwks_client_rs"
version = "0.3.0"
edition = "2021"
authors = ["Mite Ristovski <mite.ristovski@hotmail.com>", "Simone Cottini <cottini.simone@gmail.com>"]
license = "MIT"
description = "JWKS-sync client implementation for Auth0"
repository = "https://github.com/primait/jwks_client"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["sync", "macros"] }
anyhow = "1.0.44"
async-trait = "0.1.51"
jsonwebtoken = "8.0.0-beta.2"
chrono = "0.4"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
thiserror = "1.0.29"
url = "2.2"

[dev-dependencies]
mockall = "0.10"
httpmock = "0.6"
rand = "0.8"

[[example]]
name = "get_jwks"
path = "examples/get_jwks.rs"
